### ISSUE TITLE
error: when clicking favorite handler 

### ISSUE THREAD

**Issue by fiskryeziu** [rashen33/movie-app-react#14]
### Issue
Getting an error when clicking addFavouriteMovie handler (favourites is not iterable
TypeError: favourites is not iterable)

### Expected Behavior:
It should add movies to localStorage and display the favourites movies

### Current Behavior:
When clicking addFavouriteMovie handler it's throwing an error 

### Screenshots

![Capture](https://github.com/rashen33/movie-app-react/assets/64495368/bb47e71b-01e1-4e2b-aa80-e0a575695da2)

I'd like to take on this issue and work on it.

**Comment by rashen33** [comment]
Hey @fiskryeziu you can work on this. Please go ahead.

**Comment by Soyvor** [comment]
Can you assign me this issue?
