### ISSUE TITLE
Enhancement: Add Pagination

### ISSUE THREAD

**Issue by Soyvor** [rashen33/movie-app-react#7]
Description: Implement pagination for the movie list to improve user experience when there are many movies to display.
Difficulty: Easy
Labels: enhancement, frontend

**Comment by rashen33** [comment]
If you are willing to resolve this issue l can assign you.

**Comment by lunoos** [comment]
Hi @rashen33 i am willing to work on the issue can u please assign it to me.

**Comment by rashen33** [comment]
Hey @Soyvor. You can work on this. I will assign you.

**Comment by lunoos** [comment]
Hey i tried setting up the project but page is not getting loaded. It seams like the API that your using is not returning anything.

**Comment by codewithinfiver** [comment]
Hey @rashen33, I would like to work on this if you reassign!

**Comment by rashen33** [comment]
Hey @codewithinfiver the issue is currently colosed.
